theme="hugo-tracks-theme"
baseurl = "https://zetsubou.games"
languageCode = "en-us"
title = "Zetsubou's development blog"
metadataformat = "yaml"
paginate = 12 # To specify a multiple of 3
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  description = "Zetsubou's development blog" # optional
  style = "default"
  #github = "koroshiya"
  twitter = "zetsubougames"
  headerCover = "images/headerCover.png" # optional
  footerCover = "images/footerCover.png" # optional

  [[params.navlinks]]
    name = "Twitter"
    url = "https://twitter.com/ZetsubouGames"

  [params.social]
    twitter = "zetsubougames"
  

#[permalinks]
#  post = "/:year/:month/:day/:title/" # optional
